#!c:\users\francisco\documents\francisco_roj2019\sir\v_amb\sir\scripts\python.exe

print("""
The 'bokeh-server' command from versions 0.10 and earlier no longer exists.
Please see the documentation for the new 'bokeh' command here:

  http://bokeh.pydata.org/en/latest/docs/user_guide/cli.html
""")
